image: node:12
# variables:
#     NODE_ENV: 'test'
cache:
    paths:
        - node_modules/

stages:
    - lint
    - test

lint:
    stage: lint
    before_script:
        - yarn install
    script:
        - yarn lint:fix

test:
    stage: test
    before_script:
        - yarn install
    script:
        - yarn test
