image: node:12

cache:
    paths:
        - node_modules/

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    # - linting
    # - testing
    - deployment

# lint:
#     stage: linting
#     before_script:
#         - yarn install
#     script:
#         - yarn lint:fix

# test:
#     stage: testing
#     before_script:
#         - yarn install
#     script:
#         - yarn test

deploy:
    stage: deployment
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_BE --api-key=$HEROKU_API_KEY
